### PR TITLE
Add some security

### PR DESCRIPTION
**Pull request by kashima-dot-com**
It wont fully secure things but it'll avoid a few things

### CODE REVIEW

**Comment by minotaa** [comment]
ok

**Comment by minotaa** [comment]
`css-watch` & `dark-watch` is just merely to build the CSS files, it might be recommended to run them separately.

**Comment by kashima-dot-com** [comment]
Make edits as you wish.

**Comment by kashima-dot-com** [comment]
> 
> 
> `css-watch` & `dark-watch` is just merely to build the CSS files, it might be recommended to run them separately.

Btw, they are ran separately because until the process is done the other command wont run.

**Comment by minotaa** [comment]
Thank you for the PR, merging.

**Pull request merged**
