### PR TITLE
✨ Redesign of Sketchel

### PR DESCRIPTION
**Pull request by kierandrewett**

### CODE REVIEW

**Comment by minotaa** [comment]
Sounds/looks good, although a new commit is needed for this to actually be implemented.

**Comment by minotaa** [comment]
Also resolve your conflicts.

**Comment by kierandrewett** [comment]
No. You have to resolve them. It's the issues on master.

**Comment by kierandrewett** [comment]
@xMinota Resolved.

**Comment by minotaa** [comment]
Please resolve the conflicts.

**Review by VeeBack — COMMENTED** [review]
Oauth requires env too...

**Pull request merged**
